apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: kv-secret
  namespace: tripapi
spec:
  provider: azure
  parameters:
    keyvaultName: "openhackkv1216"          # the name of the KeyVault
    resourceGroup: "teamResources"
    objects:  |
      array:
        - |
          objectName: sqluser
          objectAlias: SQL_USER
          objectType: secret
        - |
          objectName: sqlpassword
          objectAlias: SQL_PASSWORD
          objectType: secret
        - |
          objectName: sqlserver
          objectAlias: SQL_SERVER
          objectType: secret
    subscriptionId: "705a85f9-a9ae-4b3f-b393-f66559b61535"
    tenantId: "dda7f574-0e26-49b3-8d16-3cc3b4a88d89"
    